{% set version = "1.0.3" %}

package:
  name: vcflib
  version: {{ version }}

source:
  url: https://github.com/vcflib/vcflib/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5fd05f46dc251a56a322809da92c93c85318036aa9ac39a2eefc4fbd39b5df6c
  patches:
    - shared_lib.patch
    - pkg-config.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - cmake
    - pkg-config
  host:
    - htslib
    - tabixpp
  run:
    - python >=3
    - zlib   
    - htslib
    - tabixpp

test:
  commands:
    - vcfallelicprimitives -h
    - vcffirstheader < /dev/null
    - vcfsort < /dev/null
    - vcfrandom | grep 'fileformat=VCF'

about:
  home: https://github.com/vcflib/vcflib
  license: MIT
  summary: Command-line tools for manipulating VCF files
  maintainers: jpuritz

extra:
  identifiers:
    - biotools:vcflib
    - doi:10.1101/023754
